name: 'Terraform Smoke Test'

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'test'

jobs:
  terraform-apply:
    name: 'Terraform-Apply'
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      env_tag: "test"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 'Terraform Initialize'
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="key=github-test.terraform.tfstate"

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Format"
        run: terraform fmt -check

      - name: "Terraform Plan"
        run: terraform plan -no-color -var="env_tag=${{ 'test' }}"

      - name: "Terraform Apply"
        run: terraform apply -var="env_tag=${{ 'test' }}" -auto-approve -input=false

      - name: "Inspect Terraform Output"
        run: terraform output storage_url

      - name: "Set CDN URL as env var"
        run: |
          OUTPUT=$(terraform output -raw storage_url)
          echo "SITE_URL=$OUTPUT" >> $GITHUB_ENV

      - name: "Set environment tag"
        run: |
          OUTPUT=$(terraform output -raw env_tag)
          echo "ENV_TAG=$OUTPUT" >> $GITHUB_ENV

      - name: "Install Package Lock Only"
        run: npm install --package-lock-only

      - name: "Install dependencies"
        run: npm ci

      - name: "Install Playwright Browsers"
        run: npx playwright install --with-deps

      - name: "Run Tests"
        run: npx playwright test

#      - name: "Upload Artifact"
#        uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30

      - name: "Terraform Destroy"
        if: always()
        run: terraform destroy -var="env_tag=${{ 'test' }}" -auto-approve