name: Terraform Unit Test
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  terraform:
    name: "Terraform Unit Test"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Init"
        run: terraform init -backend=false

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Format"
        run: terraform fmt -check -recursive

      - name: "Run Checkov"
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
